@startuml
skinparam style strictuml
skinparam linetype ortho
skinparam shadowing false
skinparam defaultTextAlignment center

skinparam nodesep 150
skinparam ranksep 50

skinparam rectangle {
  BackgroundColor #FFFFCC
  BorderColor Black
  RoundCorner 0
}

skinparam actor {
  BorderColor Black
  FontColor Black
}

title CD_UC14_01_AcessarTelaProcessamentoHolerites

actor "Usuário" as Usuario

rectangle ":MainView.fxml" as MainViewFXML
rectangle ":MainController" as MainController
rectangle ":TelaHolerite.fxml" as TelaHoleriteFXML
rectangle ":TelaHoleriteController" as TelaHoleriteController
rectangle ":ServicoCicloFolha" as ServicoCicloFolha

Usuario --> MainViewFXML : acessaTelaProcessamentoHolerites() : void

MainViewFXML -right-> MainController : 1: abrirHolerite() : void

MainController -right-> TelaHoleriteFXML : 1.1: load() : Parent

TelaHoleriteFXML ---> TelaHoleriteController : 1.2: initialize() : void

TelaHoleriteController ---> TelaHoleriteController : 1.3: carregarComboFolhas()\n: void

TelaHoleriteController ---> ServicoCicloFolha : 1.3.1: folhas := buscarTodasFolhas(): List<FolhaMes> \n 1.3.2: folhaAberta := buscarFolhaAberta(): FolhaMes



@enduml