@startuml
skinparam style strictuml
skinparam linetype ortho
skinparam shadowing false
skinparam defaultTextAlignment center

skinparam nodesep 180
skinparam ranksep 70

skinparam rectangle {
  BackgroundColor #FFFFCC
  BorderColor Black
  RoundCorner 0
}

skinparam actor {
  BorderColor Black
  FontColor Black
}

title CD_UC06_01_AcessarTelaFuncionarios

actor "Usuário" as Usuario

rectangle ":MainView.fxml" as MainViewFXML
rectangle ":MainController" as MainController
rectangle ":TelaFuncionario.fxml" as TelaFuncionarioFXML
rectangle ":TelaFuncionario" as TelaFuncionario
rectangle ":MySQLFuncionarioRepository" as MySQLFuncionarioRepository

Usuario --> MainViewFXML : acessaTelaFuncionarios() : void

MainViewFXML -right-> MainController : 1: abrirFuncionarios() : void

MainController -right-> TelaFuncionarioFXML : 1.1: load() : Parent

TelaFuncionarioFXML -right-> TelaFuncionario : 1.2: initialize() : void

TelaFuncionario ----> TelaFuncionario : 1.3: carregarDadosBanco() : void

TelaFuncionario -down-> MySQLFuncionarioRepository : 1.3.1: funcionarios := buscarTodos()\n: List<Funcionario>

@enduml