@startuml
skinparam style strictuml
skinparam linetype ortho
skinparam shadowing false
skinparam defaultTextAlignment center

skinparam nodesep 210
skinparam ranksep 100

skinparam rectangle {
  BackgroundColor #FFFFCC
  BorderColor Black
  RoundCorner 0
}

skinparam actor {
  BorderColor Black
  FontColor Black
}

title CD_UC06_03_PreencherFormularioFuncionario

actor "Usuário" as Usuario

rectangle ":CadastroFuncionarioView.fxml" as CadastroFuncionarioView

Usuario --> CadastroFuncionarioView : preencheFormulario(nome, cpf,\ncargo, salarioBruto, dataAdmissao) : void

note right of CadastroFuncionarioView
Os dados permanecem preenchidos
nos campos do formulário.
end note
@enduml