@startuml
title Colaboração - UC-11: Fechar Folha de Pagamento

rectangle "Operador" as Operador
rectangle ":TelaProcessamento" as UI
rectangle ":FolhaController" as Controller
rectangle "fp:FolhaPagamento" as Folha
rectangle "LogAuditoria" as Log

Operador -r-> UI : fecharFolha(mes)
UI -d-> Controller : 1: fecharFolha(mes)
Controller -r-> Folha : 2: setStatus("Fechada")
Controller -d-> Log : 3: registrar(usuario, data, "Fechar Folha")

@enduml
