@startuml
object ": EventoInicial" as Evento
object ": TelaProcessamento" as Tela
object ": ControladorProcessamentoFolha" as Controlador
object ": ProcessamentoFolha" as Processamento
object ": ControladorAuditoria" as Auditoria

Evento -- Tela : 1: Reconfirmacao() >

Tela -- Controlador : 2: [confirmacao == True] FecharFolha() >

Controlador -- Processamento : 3: FecharFolha(estaAberta:boolean) >

Controlador -- Auditoria : 4: RegistroAuditoria(ID : int, timestamp : Datetime, usuer : Usuario, acao : int) >
@enduml