@startuml
title Colaboração - UC-06: Cadastro de Funcionários

rectangle "Operador" as Operador
rectangle ":TelaFuncionarios" as UI
rectangle ":FuncionarioController" as Controller
rectangle "CatalogoFuncionarios" as Catalogo
rectangle "f:Funcionario" as Funcionario
rectangle "LogAuditoria" as Log

Operador -r-> UI : informarDadosFunc(pessoais, contrato)
UI -d-> Controller : 1: cadastrarFuncionario(pessoais, contrato)
Controller -r-> Catalogo : 2: f = criarFuncionario(pessoais, contrato)
Catalogo -d-> Funcionario : 3: create(pessoais, contrato)
Controller -d-> Log : 4: registrar(usuario, data, "Cadastro Funcionario")

@enduml