@startuml
object ": EventoInicial" as Evento
object ": TelaHistorico" as Tela
object ": CatalogoFolhas" as Catalogo

Evento -- Tela : 1: BuscaFolhaFunc(funcionario) >

Tela -- Catalogo : 2: Folha = BuscaFolhasProcessadasF(funcionario) : Folha >\n< 3: [F != null] ExibeFolha(F : Folha) : void
@enduml