@startuml
title Colaboração - UC-03: Atualizar dados da Empresa

rectangle "Administrador" as Admin
rectangle ":TelaEmpresa" as UI
rectangle ":ControladorEmpresa" as Controller
rectangle "e:Empresa" as Empresa
rectangle ":ControladorAuditoria" as Log

Admin -r-> UI : informarAtualizacao(cnpj : int, novosDados : String) : void
UI -d-> Controller : 1: atualizarEmpresa(cnpj : int, novosDados : String) : void
Controller -d-> Empresa : 2: setDados(novosDados : String) : void
Controller -d-> Log : 3: registroAuditoria(ID : int, timestamp : Datetime, usuer : Usuario, acao : int) : void

@enduml