@startuml
title Sequência - UC-09: Lançar Exceções Mensais

actor "Operador" as Operador
participant ":TelaLancamentos" as UI
participant ":LancamentoController" as Controller
participant "CatalogoFuncionarios" as Catalogo
participant "f:Funcionario" as Funcionario
participant "l:Lancamento" as Lancamento
participant "LogAuditoria" as Log

Operador -> UI : registrarExcecao(matricula, rubrica, valor, mes)
activate UI
UI -> Controller : addLancamento(matricula, rubrica, valor, mes)
activate Controller

Controller -> Catalogo : buscar(matricula)
activate Catalogo
Catalogo --> Controller : f
deactivate Catalogo

Controller -> Funcionario : registrarLancamento(rubrica, valor, mes)
activate Funcionario
Funcionario -> Lancamento ** : create(rubrica, valor, mes)
Funcionario --> Controller : l
deactivate Funcionario

Controller -> Log : registrar(usuario, data, "Lancar Excecao")
activate Log
Log --> Controller : ok
deactivate Log

Controller --> UI : confirmacao
deactivate Controller
UI --> Operador : exibirSucesso()
deactivate UI

@enduml
