@startuml
skinparam style strictuml
skinparam linetype ortho
skinparam shadowing false
skinparam defaultTextAlignment center

skinparam nodesep 180
skinparam ranksep 90

skinparam rectangle {
  BackgroundColor #FFFFCC
  BorderColor Black
  RoundCorner 0
}

skinparam actor {
  BorderColor Black
  FontColor Black
}

title CD_UC07_02_SelecionarFuncionarioAlteracao

actor "Usuário" as Usuario

rectangle ":TelaFuncionario.fxml" as TelaFuncionarioFXML
rectangle ":TelaFuncionario" as TelaFuncionario
rectangle ":CadastroFuncionarioView.fxml" as CadastroFuncionarioView
rectangle ":CadastroFuncionarioController" as CadastroFuncionarioController

Usuario --> TelaFuncionarioFXML : selecionaFuncionarioParaAlterarDados(funcionarioSelecionado): void

TelaFuncionarioFXML -right-> TelaFuncionario : 1: editarFuncionario() : void

TelaFuncionario -right-> CadastroFuncionarioView : 1.1: load() : Parent

CadastroFuncionarioView ---> CadastroFuncionarioController : 1.2: setFuncionarioEdicao(funcionarioSelecionado): void

@enduml