@startuml
skinparam style strictuml
skinparam linetype ortho
skinparam shadowing false
skinparam defaultTextAlignment center

skinparam nodesep 120
skinparam ranksep 100

skinparam rectangle {
  BackgroundColor #FFFFCC
  BorderColor Black
  RoundCorner 0
}

skinparam actor {
  BorderColor Black
  FontColor Black
}

title CD_UC04_03_PreencherFormularioUsuario

actor "Administrador" as Administrador

rectangle ":FormUsuario.fxml" as FormUsuarioFXML

Administrador --> FormUsuarioFXML : preencheFormulario(nomeUsuario,\nsenha, perfil) : void

note right of FormUsuarioFXML
Os dados permanecem preenchidos
nos campos do formulário.
end note
@enduml