@startuml
skinparam style strictuml
skinparam linetype ortho
skinparam shadowing false
skinparam defaultTextAlignment center

skinparam nodesep 150
skinparam ranksep 80

skinparam rectangle {
  BackgroundColor #FFFFCC
  BorderColor Black
  RoundCorner 0
}

skinparam actor {
  BorderColor Black
  FontColor Black
}

title CD_UC02_01_AcessarTelaEmpresa

actor "Administrador" as Administrador

rectangle ":MainView.fxml" as MainViewFXML
rectangle ":MainController" as MainController
rectangle ":TelaEmpresa.fxml" as TelaEmpresaFXML
rectangle ":TelaEmpresa" as TelaEmpresa
rectangle ":FormEmpresa.fxml" as FormEmpresaFXML
rectangle ":FormEmpresa" as FormEmpresa

Administrador -down-> MainViewFXML : acessaTelaEmpresa() : void

MainViewFXML -right-> MainController : 1: abrirEmpresa() : void

TelaEmpresa ---> TelaEmpresa : 1.1: exibirFormularioEmpresa(empresaAtual) : void

MainController -down-> TelaEmpresaFXML : 1.1.1: load() : Parent

TelaEmpresaFXML -right-> TelaEmpresa : 1.2: initialize() : void

TelaEmpresa -down-> FormEmpresaFXML : 1.3: exibirFormularioEmpresa(null): void

FormEmpresaFXML -right-> FormEmpresa : 1.3.1: initialize() : void

@enduml