@startuml
title Colaboração - UC-08: Cadastro de Rubricas

rectangle "Administrador" as Admin
rectangle ":TelaRubricas" as UI
rectangle ":RubricaController" as Controller
rectangle "CatalogoRubricas" as Catalogo
rectangle "r:Rubrica" as Rubrica
rectangle "LogAuditoria" as Log

Admin -r-> UI : informarRubrica(tipo, regras, incidencias)
UI -d-> Controller : 1: cadastrarRubrica(tipo, regras, incidencias)
Controller -r-> Catalogo : 2: r = criarRubrica(tipo, regras, incidencias)
Catalogo -d-> Rubrica : 3: create(tipo, regras, incidencias)
Controller -d-> Log : 4: registrar(usuario, data, "Cadastro Rubrica")

@enduml