@startuml
title Colaboração - UC-08: Cadastro de Rubricas

rectangle "Administrador" as Admin
rectangle ":TelaRubricas" as UI
rectangle ":ControladorRubricas" as Controller
rectangle "CatalogoRubricas" as Catalogo
rectangle "r:Rubrica" as Rubrica
rectangle ":ControladorAuditoria" as Log

Admin -r-> UI : informarRubrica(tipo : int, regras : String, incidencias : int) : void 
UI -d-> Controller : 1: cadastrarRubrica(tipo : int, regras : String, incidencias : int) : void
Controller -r-> Catalogo : 2: r = criarRubrica(tipo : int, regras : String, incidencias : int) : Rubrica
Catalogo -d-> Rubrica : 3: create(tipo : int, regras : String, incidencias : int)  : void
Controller -d-> Log : 4: registroAuditoria(ID : int, timestamp : Datetime, usuer : Usuario, acao : int) : void

@enduml