@startuml 

actor "Analista de RH" as RH 
rectangle "Controlador de Parâmetros Legais" as Controller 
rectangle "Repositório de Parâmetros Legais" as RepoParametros 

RH -right-> Controller : 1. Solicita dados dos parâmetros legais

Controller -> RepoParametros : 2. Busca dados dos parâmetros legais 

RepoParametros -> Controller : 2.1 Retorna os dados dos parâmetros legais

Controller -> RH : 3. Exibe dados dos parâmetros legais

RH -> Controller : 4. Insere novos dados e clica em "Salvar"

Controller -> RepoParametros : 5. Atualiza dados dos parâmetros legais

RepoParametros -> Controller : 5.1 Dados atualizados com sucesso

Controller -> RH : 6. Exibe mensagem de sucesso.

@enduml