@startuml 

actor "Analista de RH" as RH 
participant "Controlador de Parâmetros Legais" as Controller
participant "Repositório de Parâmetros Legais" as RepoParametros 

RH -> Controller : 1. Solicita dados dos parâmetros legais
activate Controller 

Controller -> RepoParametros : 2. Busca dados dos parâmetros legais 
activate RepoParametros 

RepoParametros -> Controller : 2.1 Retorna os dados dos parâmetros legais
deactivate RepoParametros 

Controller -> RH : 3. Exibe dados dos parâmetros legais
deactivate Controller

RH -> Controller : 4. Insere novos dados e clica em "Salvar"
activate Controller 

Controller -> RepoParametros : 5. Atualiza dados dos parâmetros legais
activate RepoParametros 

RepoParametros -> Controller : 5.1 Dados atualizados com sucesso
deactivate RepoParametros 

Controller --> RH : 6. Exibe mensagem de sucesso.
deactivate Controller 

@enduml




