@startuml
title Colaboração - UC-10: Processar Folha de Pagamento

rectangle "Operador" as Operador
rectangle ":TelaProcessamento" as UI
rectangle ":FolhaController" as Controller
rectangle "CatalogoFuncionarios" as Catalogo
rectangle "f:Funcionario" as Funcionario
rectangle "fp:FolhaPagamento" as Folha
rectangle "LogAuditoria" as Log

Operador -r-> UI : processarFolha(mes)
UI -d-> Controller : 1: processarFolha(mes)
Controller -r-> Catalogo : 2: lista = getAtivos()
Controller -d-> Funcionario : 3: fp = calcularFolha(mes)
Funcionario -d-> Folha : 4: create()
Funcionario -d-> Folha : 5: addProventosDescontos()
Controller -d-> Log : 6: registrar(usuario, data, "Processar Folha")

@enduml
