@startuml
object ": EventoInicial" as Evento
object ": TelaProcessamento" as Tela
object ": ControladorProcessamentoFolha" as Controlador
object ": ProcessamentoFolha" as Processamento
object ": Funcionarios" as Funcionarios
object ": Lancamento" as Lancamento
object ": ParametrosLegais" as Parametros
object ": ControladorAuditoria" as Auditoria

Evento -- Tela : 1: ProcessarFolha() >

Tela -- Controlador : 2: ProcessamentoFolha() >\n< 11: ResumoConsolidado(funcionariosProventos,Descontos,TotalLiquido,TotalEncargos)

Controlador -- Funcionarios : 3: F = ObterFuncionarios() : <ArrayList> >

Controlador -- Lancamento : 7: Ex = ObtemExcecoes(F) : <ArrayList> >

Controlador -- Parametros : 8: Al = ObtemAliquotas(F) : <ArrayList> >

Controlador -- Auditoria : < 12: RegistroAuditoria(ID : int, timestamp : Datetime, usuario : Usuario, acao : int)

Controlador -- Processamento : 4: [1..*] Vd = CalcValorDia(F : <ArrayList>) : <ArrayList> >\n5: [1..*] Vh = CalcValorHora(F : <ArrayList>) : <ArrayList> >\n6: [1..*] SB = CalcSalarioBruto() : <ArrayList> >\n9: [1..*] SL = CalcSalarioLiquido(VD,VH,EX,AL) : <ArrayList> >\n10: [1..*] Prov = CalcProvisoes(F : Funcionarios) : <ArrayList> >
@enduml