@startuml
skinparam style strictuml
skinparam linetype ortho
skinparam shadowing false
skinparam defaultTextAlignment center

skinparam nodesep 110
skinparam ranksep 90

skinparam rectangle {
  BackgroundColor #FFFFCC
  BorderColor Black
  RoundCorner 0
}

skinparam actor {
  BorderColor Black
  FontColor Black
}

title CD_UC15_02_FiltrarRegistrosAuditoria

actor "Administrador" as Administrador

rectangle ":TelaLog.fxml" as TelaLogFXML
rectangle ":TelaLog" as TelaLog
rectangle ":ControladorAuditoria" as ControladorAuditoria
rectangle ":MySQLAuditoriaRepository" as MySQLAuditoriaRepository

Administrador --> TelaLogFXML : filtraRegistrosAuditoria(usuario,dataInicial, dataFinal) : void

TelaLogFXML -right-> TelaLog : 1: buscar() : void

TelaLog --> ControladorAuditoria : 1.1: registros := buscar(usuarioNome, data): List<RegistroAuditoria>

ControladorAuditoria --> MySQLAuditoriaRepository : 1.1.1: registros := buscar(usuario, data): List<RegistroAuditoria>

TelaLog ---> TelaLog : 1.2: setItems(obsList): void

@enduml