@startuml
title Sequência - UC-17: Atualização de Parâmetros Legais

actor "Operador" as Operador
participant ":TelaParametros" as UI
participant ":ParametrosController" as Controller
participant "p:ParametrosLegais" as Parametros
participant "LogAuditoria" as Log

Operador -> UI : atualizarParametros(novosParametros)
activate UI
UI -> Controller : atualizarParametros(novosParametros)
activate Controller

Controller -> Parametros : setValores(novosParametros)
activate Parametros
Parametros --> Controller : ok
deactivate Parametros

Controller -> Log : registrar(usuario, data, "Atualizar Parametros")
activate Log
Log --> Controller : ok
deactivate Log

Controller --> UI : confirmacao
deactivate Controller
UI --> Operador : exibirSucesso()
deactivate UI

@enduml
