@startuml
object ": EventoInicial" as Evento
object ": TelaParametros" as Tela
object ": ParâmetrosLegais" as Parametros
object ": ControladorAuditoria" as Auditoria

Evento -- Tela : 1: AlteracaoPL(Parametro : <ArrayList>) >

Tela -- Parametros : 2: [Confirmacao == True] AlteracoesPL(Parametro : ArrayList) >\n< 3: MensagemSucesso()

Tela -- Auditoria : 4: RegistroAuditoria(ID : int, timestamp : Datetime, usuer : Usuario, acao : int) >
@enduml