@startuml
title Colaboração - UC-12: Emitir Holerites

rectangle "Operador" as Operador
rectangle ":TelaHolerite" as UI
rectangle ":HoleriteController" as Controller
rectangle "CatalogoFuncionarios" as Catalogo
rectangle "f:Funcionario" as Funcionario
rectangle "h:Holerite" as Holerite

Operador -r-> UI : consultarHolerite(matricula, mes)
UI -d-> Controller : 1: gerarHolerite(matricula, mes)
Controller -r-> Catalogo : 2: f = buscar(matricula)
Controller -d-> Funcionario : 3: fp = getFolha(mes)
Controller -d-> Holerite : 4: h = create(f, fp)

@enduml
