@startuml
object ": EventoInicial" as Evento
object ": TelaHolerite" as Tela
object ": ControladorHolerite" as Controlador
object ": CatalogoFolhas" as Catalogo

Evento -- Tela : 1: AcessaHolerite() >

Tela -- Controlador : 2: Create() >\n< 3: ExibeListaFolhas(Folha: Folha)

Controlador -- Catalogo : 4: Folha = FolhasFechadas() : ArrayList >
@enduml