@startuml
object ": EventoInicial" as Evento
object ": TelaHolerite" as Tela
object ": ControladoreHolerite" as Controlador
object ": CatalogoFolhas" as Catalogo
object ": ControladorAuditoria" as Auditoria
object ": Holerite" as Holerite
object ": Holerite_Rubrica" as HoleriteRubrica
object ": Rubrica" as Rubrica

Evento -- Tela : 1: EmissaoHolerite(mes,funcionario) >

Tela -- Controlador : 2: [isFechada == True] EmitirHolerite(mes,funcionario) >\n< 7: ExibeHolerite(holerite)

Controlador -- Catalogo : 3: BuscaFolhasProcessadasD(mes : Datetime) : Folha >

Controlador -- Auditoria : 8: RegistroAuditoria(ID : int, timestamp : Datetime, usuer : Usuario, acao : int) >

Controlador -- Holerite : 4: holerite = GerarHolerite(mes,funcionario) >

Holerite -- HoleriteRubrica : 5: RubricasIncidentes(rubrica : Rubrica, referencia : String, valor : double) >

HoleriteRubrica -- Rubrica : 6: cod = CodigoRubrica() : Integer >
@enduml