@startuml
skinparam style strictuml
skinparam linetype ortho
skinparam shadowing false
skinparam defaultTextAlignment center

skinparam nodesep 150
skinparam ranksep 50

skinparam rectangle {
  BackgroundColor #FFFFCC
  BorderColor Black
  RoundCorner 0
}

skinparam actor {
  BorderColor Black
  FontColor Black
}

title CD_UC03_01_AcessarTelaEmpresa

actor "Administrador" as Administrador

rectangle ":MainView.fxml" as MainViewFXML
rectangle ":MainController" as MainController
rectangle ":TelaEmpresa.fxml" as TelaEmpresaFXML
rectangle ":TelaEmpresa" as TelaEmpresa
rectangle ":ControladorEmpresa" as ControladorEmpresa
rectangle ":MySQLEmpresaRepository" as MySQLEmpresaRepository


TelaEmpresaFXML -[hidden]down- TelaEmpresa
TelaEmpresa -[hidden]down- ControladorEmpresa
ControladorEmpresa -[hidden]down- MySQLEmpresaRepository

Administrador -down-> MainViewFXML : acessaTelaEmpresa() : void

MainViewFXML -right-> MainController : 1: abrirEmpresa() : void

TelaEmpresa -right-> TelaEmpresa : 1.1: exibirFormularioEmpresa(empresaAtual) : void\n 1.3: carregarEmpresa() : void \n1.4: exibirEmpresaSelecionada(): void

MainController -right-> TelaEmpresaFXML : 1.1.1: load() : Parent

TelaEmpresaFXML --> TelaEmpresa : 1.2: initialize() : void



TelaEmpresa ---> ControladorEmpresa : 1.3.1: empresa := buscarEmpresa(): Empresa

ControladorEmpresa --> MySQLEmpresaRepository : 1.3.1.1: empresa := buscarEmpresaUnica(): Empresa


@enduml