@startuml

actor "Analista de RH" as RH
participant "Controlador do Cadastro de Funcionário" as Controller
participant "Funcionário Repositório" as RepoFuncionario

RH -> Controller : 1. Solicita cadastro de funcionário
activate Controller

Controller -> RH : 1.1. Retorna a tela de cadastro de funcionário.

RH -> Controller : 2. Preenche os dados e clica em "Salvar"

create Funcionario 
Controller -> Funcionario : <<create>> (nome, cpf, salario, cargo, data_admissao, status)

Controller -> RepoFuncionario : 3. salvar(funcionario).
activate RepoFuncionario

RepoFuncionario -> Controller :  3.1 true (sucesso)
deactivate RepoFuncionario

Controller --> RH: 4. Exibe mensagem de sucesso.
deactivate Controller

@enduml