@startuml
title Colaboração - UC-05: Atualizar Usuários no Sistema

rectangle "Administrador" as Admin
rectangle ":TelaUsuarios" as UI
rectangle ":UsuarioController" as Controller
rectangle "CatalogoUsuarios" as Catalogo
rectangle "u:Usuario" as Usuario
rectangle "LogAuditoria" as Log

Admin -r-> UI : alterarUsuario(id, novosDados, status)
UI -d-> Controller : 1: atualizarUsuario(id, novosDados, status)
Controller -r-> Catalogo : 2: u = buscar(id)
Controller -d-> Usuario : 3: setAtributos(novosDados, status)
Controller -d-> Log : 4: registrar(usuario, data, "Atualizar Usuario")

@enduml