@startuml
title Colaboração - UC-05: Atualizar Usuários no Sistema

rectangle "Administrador" as Admin
rectangle ":TelaUsuarios" as UI
rectangle ":ControladorUsuarios" as Controller
rectangle "CatalogoUsuarios" as Catalogo
rectangle "u:Usuario" as Usuario
rectangle ":ControladorAuditoria" as Log

Admin -r-> UI : alterarUsuario(id : int, novosDados : String, status : String) : void
UI -d-> Controller : 1: atualizarUsuario(id : int, novosDados : String, status : String) : void
Controller -r-> Catalogo : 2: u = buscar(id : int) : Usuario
Controller -d-> Usuario : 3: setAtributos(novosDados : String, status : String) : void
Controller -d-> Log : 4: registroAuditoria(ID : int, timestamp : Datetime, usuer : Usuario, acao : int) : void

@enduml