@startuml
title Sequência - UC-05: Atualizar Usuários no Sistema

actor "Administrador" as Admin
participant ":TelaUsuarios" as UI
participant ":UsuarioController" as Controller
participant "CatalogoUsuarios" as Catalogo
participant "u:Usuario" as Usuario
participant "LogAuditoria" as Log

Admin -> UI : alterarUsuario(id, novosDados, status)
activate UI
UI -> Controller : atualizarUsuario(id, novosDados, status)
activate Controller

Controller -> Catalogo : buscar(id)
activate Catalogo
Catalogo --> Controller : u
deactivate Catalogo

Controller -> Usuario : setAtributos(novosDados, status)
activate Usuario
Usuario --> Controller : ok
deactivate Usuario

Controller -> Log : registrar(usuario, data, "Atualizar Usuario")
activate Log
Log --> Controller : ok
deactivate Log

Controller --> UI : confirmacao
deactivate Controller
UI --> Admin : exibirSucesso()
deactivate UI

@enduml
