@startuml
title Colaboração - UC-07: Atualizar dados de Funcionários

rectangle "Operador" as Operador
rectangle ":TelaFuncionarios" as UI
rectangle ":ControladorFuncionarios" as Controller
rectangle "CatalogoFuncionarios" as Catalogo
rectangle "f:Funcionario" as Funcionario
rectangle ":ControladorAuditoria" as Log

Operador -r-> UI : alterarFuncionario(matricula : int, novosDados : String, status : String) : void
UI -d-> Controller : 1: atualizarFuncionario(matricula : int, novosDados : String, status : String) : void
Controller -r-> Catalogo : 2: f = buscar(matricula : int) : Funcionarios
Controller -d-> Funcionario : 3: setDados(novosDados : String, status : String) : void
Controller -d-> Log : 4: registroAuditoria(ID : int, timestamp : Datetime, usuer : Usuario, acao : int) : void
@enduml