@startuml
object ": EventoInicial" as Evento
object ": TelaRelatorio" as Tela
object ": ControladorProcessamentoFolha" as Controlador
object ": ProcessamentoFolha" as Processamento
object ": ControladorAuditoria" as Auditoria

Evento -- Tela : 1: SelecionaRelatorio(TipoRel) >

Tela -- Controlador : 2: TipoRelatorio(TipoRel) >\n< 5: [Relatorio != null] Exibe(Relatorio)

Controlador -- Processamento : 3: estaAberta = isAberta() : boolean >\n4: [estaAberta == False] Relatorio = GerarRelatorio(TipoRel) : Relatorio >

Controlador -- Auditoria : 6: RegistroAuditoria(ID : int, timestamp : Datetime, usuer : Usuario, acao : int) >
@enduml