@startuml
title Colaboração - UC-16: Consultar Log de Auditoria

rectangle "Administrador" as Admin
rectangle ":TelaAuditoria" as UI
rectangle ":AuditoriaController" as Controller
rectangle "LogAuditoria" as Log

Admin -r-> UI : buscarLog(periodo, usuario, acao)
UI -d-> Controller : 1: consultarLog(periodo, usuario, acao)
Controller -r-> Log : 2: logs = buscar(periodo, usuario, acao)

@enduml
