@startuml
title Colaboração - UC-02: Cadastro da Empresa

rectangle "Administrador" as Admin
rectangle ":TelaCadastroEmpresa" as UI
rectangle ":ControladorEmpresa" as Controller
rectangle "e:Empresa" as Empresa
rectangle ":ControladorAuditoria" as Log

Admin -r-> UI : informarDados(cnpj : int , razaoSocial : String, endereco : String, respLegal : String) :void
UI -d-> Controller : 1: cadastrarEmpresa(cnpj : int, razaoSocial : String, endereco : String, respLegal : String) : void
Controller -d-> Empresa : 2: create(cnpj : int, razaoSocial : String, endereco : String, respLegal : String) : void
Controller -d-> Log : 3: registroAuditoria(ID : int, timestamp : Datetime, usuer : Usuario, acao : int) : void
@enduml