@startuml
title Sequência - UC-12: Emitir Holerites

actor "Operador" as Operador
participant ":TelaHolerite" as UI
participant ":HoleriteController" as Controller
participant "CatalogoFuncionarios" as Catalogo
participant "f:Funcionario" as Funcionario
participant "h:Holerite" as Holerite

Operador -> UI : consultarHolerite(matricula, mes)
activate UI
UI -> Controller : gerarHolerite(matricula, mes)
activate Controller

Controller -> Catalogo : buscar(matricula)
activate Catalogo
Catalogo --> Controller : f
deactivate Catalogo

Controller -> Funcionario : getFolha(mes)
activate Funcionario
Funcionario --> Controller : fp
deactivate Funcionario

Controller -> Holerite ** : create(f, fp)

Controller --> UI : h
deactivate Controller
UI --> Operador : exibirHolerite(h)
deactivate UI

@enduml
