@startuml
skinparam style strictuml
skinparam linetype ortho
skinparam shadowing false
skinparam defaultTextAlignment center

skinparam nodesep 265
skinparam ranksep 80

skinparam rectangle {
  BackgroundColor #FFFFCC
  BorderColor Black
  RoundCorner 0
}

skinparam actor {
  BorderColor Black
  FontColor Black
}

title CD_UC11_04_ConfirmarAtualizacaoLancamento

actor "Usuário" as Usuario

rectangle ":FormLancamento.fxml" as FormLancamentoFXML
rectangle ":FormLancamentoController" as FormLancamentoController
rectangle ":MySQLLancamentoRepository" as MySQLLancamentoRepository
rectangle ":TelaLancamento" as TelaLancamento

Usuario -[hidden]down- FormLancamentoFXML
FormLancamentoController -[hidden]down- MySQLLancamentoRepository


Usuario ---> FormLancamentoFXML : confirmaAtualizacaoLancamento() : void

FormLancamentoFXML -right-> FormLancamentoController : 1: salvar() : void

FormLancamentoController ---> MySQLLancamentoRepository : 1.1: atualizar(lancamentoEditado): void\n1.4.1: lancamentos := buscarPorFolha(idFolha): List<Lancamento>

FormLancamentoController ---> FormLancamentoController : 1.2: fecharJanela() : void

TelaLancamento ---> TelaLancamento : 1.3: atualizarTabela(funcionarioFiltro): void

TelaLancamento -left-> MySQLLancamentoRepository : 1.4: lancamentos := buscarPorFolha(idFolha)\n: List<Lancamento>

@enduml