@startuml
title Colaboração - UC-01: Autenticar no sistema

rectangle "Operador" as Operador
rectangle ":TelaLogin" as UI
rectangle ":ControladorAutenticacao" as Controller
rectangle "CatalogoUsuarios" as Catalogo
rectangle "u:Usuario" as Usuario
rectangle ":ControladorAuditoria" as Log

Operador -r-> UI : informarCredenciais(usuario : String, senha : String) :void
UI -d-> Controller : 1: login(usuario : String, senha : String) : void
Controller -r-> Catalogo : 2: u = buscar(usuario : String) : Usuario
Controller -d-> Usuario : 3: isValid = validarSenha(senha : String) : boolean
Controller -d-> Log : 4: registroAuditoria(ID : int, timestamp : Datetime, usuer : Usuario, acao : int) : void

@enduml