@startuml
skinparam style strictuml

actor "Analista de RH" as RH
rectangle "Controlador da Folha" as Controller
rectangle "Processador da Folha" as Processador
rectangle "Regra de Calculo" as Regra

RH -> Controller : 1 processar()
Controller -> Processador : 1.1: calcular(funcionario)
Processador -> Processador : 1.2: para cada regra
Processador -> Regra : 1.2.1: calcular(funcionario)
Regra --> Processador : 1.2.2: valorCalculado
Processador -> Controller : 1.3: holerite
Controller --> RH : 2 visualiza holerite
RH -> Controller : 3 confirmar
Controller --> RH : 4 confirmar processamento

@enduml