@startuml
autonumber 

actor "Analista de RH" as RH
participant "Controlador da Folha" as Controller
participant "Processador da Folha" as Processador
participant "regra:RegraDeCalculo" as Regra

RH -> Controller : Inicia processamento da folha
activate Controller
Controller -> Processador : processar(funcionario) 
activate Processador

loop Para cada regra de calculo
    Processador -> Regra : calcular(funcionario)
    activate Regra 
    Regra -> Processador : valorCalculado
    deactivate Regra
end

Processador -> Controller : holerite
deactivate Processador
deactivate Controller

RH -> RH : Visualiza Holerite
RH -> Controller : Confirmar processamento
activate Controller 
Controller -> RH : Holerite processado
deactivate Controller

@enduml