@startuml
title Colaboração - UC-03: Atualizar dados da Empresa

rectangle "Administrador" as Admin
rectangle ":TelaEmpresa" as UI
rectangle ":EmpresaController" as Controller
rectangle "e:Empresa" as Empresa
rectangle "LogAuditoria" as Log

Admin -r-> UI : informarAtualizacao(cnpj, novosDados)
UI -d-> Controller : 1: atualizarEmpresa(cnpj, novosDados)
Controller -d-> Empresa : 2: setDados(novosDados)
Controller -d-> Log : 3: registrar(usuario, data, "Atualizar Empresa")

@enduml