
@startuml
object ": EventoInicial" as Evento
object ": TelaProcessamento" as Tela
object ": ControladorProcessamentoFolha" as Controlador
object ": ProcessamentoFolha" as Processamento

Evento -- Tela : 1: AcessaProcessamentoFolha() >
Tela -- Controlador : 2: Create() >
Controlador -- Tela : 6: [isAberta == True AND possuiFuncionario == True] ExibePainel() >

Controlador -- Processamento : 3: Create() >\n4: folha_aberta = isAberta() : boolean >\n5: tem_funcionario = possuiFuncionario() : boolean >
@enduml