@startuml
title Sequência - UC-10: Processar Folha de Pagamento

actor "Operador" as Operador
participant ":TelaProcessamento" as UI
participant ":FolhaController" as Controller
participant "CatalogoFuncionarios" as Catalogo
participant "f:Funcionario" as Funcionario
participant "fp:FolhaPagamento" as Folha
participant "LogAuditoria" as Log

Operador -> UI : processarFolha(mes)
activate UI
UI -> Controller : processarFolha(mes)
activate Controller

Controller -> Catalogo : getAtivos()
activate Catalogo
Catalogo --> Controller : listaAtivos
deactivate Catalogo

loop Para cada Funcionario na listaAtivos
    Controller -> Funcionario : calcularFolha(mes)
    activate Funcionario
    
    Funcionario -> Folha ** : create()
    Funcionario -> Folha : addProventosDescontos()
    activate Folha
    Folha --> Funcionario : ok
    deactivate Folha
    
    Funcionario --> Controller : fp
    deactivate Funcionario
end

Controller -> Log : registrar(usuario, data, "Processar Folha")
activate Log
Log --> Controller : ok
deactivate Log

Controller --> UI : resumoConsolidado
deactivate Controller
UI --> Operador : exibirResumo()
deactivate UI

@enduml
