@startuml
title Colaboração - UC-04: Cadastro de Usuários do Sistema

rectangle "Administrador" as Admin
rectangle ":TelaUsuarios" as UI
rectangle ":ControladorUsuarios" as Controller
rectangle "CatalogoUsuarios" as Catalogo
rectangle "u:Usuario" as Usuario
rectangle ":ControladorAuditoria" as Log

Admin -r-> UI : informarDadosUsuario(nomeUsuario : String, senha : String, perfil : String) : void
UI -d-> Controller : 1: cadastrarUsuario(nomeUsuario : String, senha : String, perfil : String) : void
Controller -r-> Catalogo : 2: u = criarUsuario(nomeUsuario : String, senha : String, perfil : String) : Usuario
Catalogo -d-> Usuario : 3: create(nomeUsuario : String, senha : String, perfil : String) : void
Controller -d-> Log : 4: registroAuditoria(ID : int, timestamp : Datetime, usuer : Usuario, acao : int) : void

@enduml