@startuml
object ": EventoInicial" as Evento
object ": TelaHolerite" as Tela
object ": ControladorHolerite" as Controlador
object ": ControladorAuditoria" as Auditoria

Evento -- Tela : 1: SelecionaDiretorio(nomeArquivo : String, diretorio : String) >

Tela -- Controlador : 2: SalvarArquivo(arquivo : String, diretorio : String) >\n< 3: [salvo == True] MensagemSucesso()

Controlador -- Auditoria : 4: RegistroAuditoria(ID : int, timestamp : Datetime, usuer : Usuario, acao : int) >
@enduml