@startuml
object ": EventoInicial" as Evento
object ": TelaHolerite" as Tela
object ": ControladorHolerite" as Controlador
object ": Holerite" as Holerite

Evento -- Tela : 1: AcessaHolerite(holerite) >

Tela -- Controlador : 2: BuscaHoleriteEmitido(holerite) >\n< 5: [estaFechado == True] ExibeHolerite(holerite)

Controlador -- Holerite : 3: estaFechado = isFechado() : boolean >\n4: BuscaHolerite(holerite) >
@enduml