@startuml
title Colaboração - UC-17: Atualização de Parâmetros Legais

rectangle "Operador" as Operador
rectangle ":TelaParametros" as UI
rectangle ":ParametrosController" as Controller
rectangle "p:ParametrosLegais" as Parametros
rectangle "LogAuditoria" as Log

Operador -r-> UI : atualizarParametros(novosParametros)
UI -d-> Controller : 1: atualizarParametros(novosParametros)
Controller -r-> Parametros : 2: setValores(novosParametros)
Controller -d-> Log : 3: registrar(usuario, data, "Atualizar Parametros")

@enduml
