@startuml
title Sequência - UC-06: Cadastro de Funcionários

actor "Operador" as Operador
participant ":TelaFuncionarios" as UI
participant ":FuncionarioController" as Controller
participant "CatalogoFuncionarios" as Catalogo
participant "f:Funcionario" as Funcionario
participant "LogAuditoria" as Log

Operador -> UI : informarDadosFunc(pessoais, contrato)
activate UI
UI -> Controller : cadastrarFuncionario(pessoais, contrato)
activate Controller

Controller -> Catalogo : criarFuncionario(pessoais, contrato)
activate Catalogo
Catalogo -> Funcionario ** : create(pessoais, contrato)
Catalogo --> Controller : f
deactivate Catalogo

Controller -> Log : registrar(usuario, data, "Cadastro Funcionario")
activate Log
Log --> Controller : ok
deactivate Log

Controller --> UI : confirmacao
deactivate Controller
UI --> Operador : exibirSucesso()
deactivate UI

@enduml
